on:
  pull_request:
  # Allow manually triggered workflows by maintainers without any
  # parameters to trigger a proactive rebuild (e.g. when a new
  # apko lands)
  workflow_dispatch: {}

name: test


jobs:
  build:
    name: Release OCI image
    runs-on: ubuntu-latest

    outputs:
      image-refs: ${{ steps.emit-refs.outputs.image-refs }}

    strategy:
      matrix:
        nginx-version: [1.20.2, 1.23.0]
        include:
          - nginx-version: 1.20.2
            sha256: 958876757782190a1653e14dc26dfc7ba263de310e04c113e11e97d1bef45a42
          - nginx-version: 1.23.0
            sha256: 820acaa35b9272be9e9e72f6defa4a5f2921824709f8aa4772c78ab31ed94cd1

    steps:
    - uses: actions/checkout@v3


    - name: Emit Image Refs output
      id: emit-refs
      run: |
        echo ::set-output name=image-refs::${{ matrix.nginx-version }})
        ::echo::on

  scan:
    name: Scan apko images
    needs: build
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    strategy:
      matrix:
        ref: ${{ fromJson(needs.build.outputs.image-refs) }}
    steps:
    - run: |
        echo ${{ matrix.ref }}
